# Render asignar\u00e1 el puerto autom\u00e1ticamente
server.port=${PORT:8080}

# Conexi\u00f3n din\u00e1mica a la base de datos
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Para que Spring cree o actualice las tablas autom\u00e1ticamente
spring.jpa.hibernate.ddl-auto=update