# Configuraci\u00f3n din\u00e1mica para Cloud (Render) y Local
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/sgi_db?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:root}

# Configuraci\u00f3n de Hibernate
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=true

# Desactivar cach\u00e9 de Thymeleaf para despliegue
spring.thymeleaf.cache=false
