# Configuración dinámica (Cloud-Ready)
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/sgi_db?serverTimezone=UTC&useSSL=true&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:root}

# Configuración de JPA y Hibernate
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=true
spring.thymeleaf.cache=false
